name: MarkUs Tests
on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
  push:
    branches:
      - master

jobs:
  setup:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-22.04
    outputs:
      cache-key: ${{ steps.pip-cache.outputs.dir }}
    services:
      postgres:
        image: postgres:14
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: markus_test
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
      redis:
        image: redis
        ports:
          - 6379:6379
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
          --entrypoint redis-server
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get -yqq install libpq-dev cmake ghostscript pandoc imagemagick libmagickwand-dev git libgl1 tesseract-ocr pandoc
      - name: Set up ruby and cache gems
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ruby-3.3
          bundler-cache: true
      - name: Set up node and cache packages
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: npm
      - name: Install npm packages
        run: npm ci
      - name: Install python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - name: Get pip cache dir
        id: pip-cache
        run: |
          echo "dir=$(pip cache dir)" >> $GITHUB_OUTPUT
      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ${{ steps.pip-cache.outputs.dir }}
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements-jupyter.txt') }}-${{ hashFiles('requirements-scanner.txt') }}-${{ hashFiles('requirements-qr.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: Cache playwright's installation of Chromium
        uses: actions/cache@v4
        with:
          path: ~/.cache/ms-playwright
          key: ${{ runner.os }}-playwright-${{ hashFiles('requirements-jupyter.txt') }}
          restore-keys: |
            ${{ runner.os }}-playwright-
      - name: Install python packages and playwright dependencies
        run: |
          python3.10 -m venv venv
          ./venv/bin/pip install -r requirements-jupyter.txt -r requirements-scanner.txt -r requirements-qr.txt
          ./venv/bin/playwright install chromium
          ./venv/bin/playwright install-deps chromium
      - name: Install chromedriver
        uses: nanasess/setup-chromedriver@v2
      - name: Run chromedriver
        run: chromedriver --port=9515 --whitelisted-ips &

  rspec:
    needs: setup
    runs-on: ubuntu-22.04
    env:
      RAILS_ENV: test
      MARKUS__PYTHON: ./venv/bin/python3
      BUNDLE_WITHOUT: development:production:console:unicorn
    steps:
      - uses: actions/checkout@v4
      - name: Build assets and DB
        run: |
          bundle exec rake javascript:build
          bundle exec rake css:build
          bundle exec rails db:migrate
      - name: Run rspec tests
        run: bundle exec rspec
      - name: Run rspec system tests
        run: bundle exec rspec spec/system
      - name: Coveralls Parallel (rspec)
        uses: coverallsapp/github-action@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          flag-name: rspec
          parallel: true
          file: coverage/lcov.info

  jest:
    needs: setup
    runs-on: ubuntu-22.04
    env:
      NODE_ENV: test
    steps:
      - uses: actions/checkout@v4
      - name: Run jest tests
        run: npm run test-cov
      - name: Coveralls Parallel (jest)
        uses: coverallsapp/github-action@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          flag-name: jest
          parallel: true
          file: coverage/lcov.info

  finish:
    needs: [rspec, jest]
    runs-on: ubuntu-22.04
    permissions:
      pull-requests: write
    steps:
      - name: Coveralls Finished
        uses: coverallsapp/github-action@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          parallel-finished: true
          carryforward: "rspec,jest"
